
---
website_title:   'Wouter Kayser'
website_tagline: 'Personal home page for Wouter Kayser'
title: 'Wouter Kayser'
date:   4th January 2020
author:
  - Wouter Kayser
description: 'Simple Homepage for Wouter Kayser'
keywords:
  - Wouter Kayser
  - Electrical Engineering
  - IoT
  - 5G
  - M2M
...